services:
  server-simulator:
    environment:
      save: "true"
      load: "true"
      redis_address: "redis"
      redis_port: "6379"
    image: wordluc/sand-mmo-server:latest
    deploy:
      mode: global
    depends_on:
      - redis
    build:
      context: .
      dockerfile: server/Dockerfile

    ports:
      - "8000:8000"
  web:
    deploy:
      mode: replicated
      replicas: 1
    image: wordluc/sand-mmo-web:latest
    build:
      context: .
      dockerfile: wasm_client/Dockerfile

    ports:
      - "80:80"
  redis:
    env_file: ".env"
    image: redis
    environment:
      - REDIS_PASSWORD
    command: ["sh", "-c", "redis-server --requirepass $$REDIS_PASSWORD"]
    ports:
      - "6000:6379"
    volumes:
      - redis-data:/data
    deploy:
      mode: global

volumes:
    redis-data:

