services:
  server-simulator:
    image: wordluc/sand-mmo-server:latest
    deploy:
      mode: global
    depends_on:
      - redis
    build:
      context: .
      dockerfile: server/Dockerfile

    ports:
      - "8000:8000"
  web:
    deploy:
      mode: replicated
      replicas: 1
    image: wordluc/sand-mmo-web:latest
    build:
      context: .
      dockerfile: wasm_client/Dockerfile

    ports:
      - "8080:8080"
  redis:
    deploy:
      mode: global
    image: redis
    ports:
      - "6000:6379"
    volumes:
      - redis-data:/data
volumes:
    redis-data:

